# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt4 UI code generator 4.12.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(570, 490)
        MainWindow.setMinimumSize(QtCore.QSize(570, 490))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 541, 441))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.stackedWidgetPage1 = QtGui.QWidget()
        self.stackedWidgetPage1.setObjectName(_fromUtf8("stackedWidgetPage1"))
        self.verticalLayoutWidget = QtGui.QWidget(self.stackedWidgetPage1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 531, 431))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.frame = QtGui.QFrame(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(350, 300))
        self.frame.setMaximumSize(QtCore.QSize(300, 300))
        self.frame.setBaseSize(QtCore.QSize(300, 300))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 30, 171, 80))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.NameLine = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.NameLine.setObjectName(_fromUtf8("NameLine"))
        self.verticalLayout_2.addWidget(self.NameLine)
        self.PasswordLine = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.PasswordLine.setEchoMode(QtGui.QLineEdit.Password)
        self.PasswordLine.setObjectName(_fromUtf8("PasswordLine"))
        self.verticalLayout_2.addWidget(self.PasswordLine)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(89, 179, 193, 100))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.RemindMeFlag = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.RemindMeFlag.setTristate(False)
        self.RemindMeFlag.setObjectName(_fromUtf8("RemindMeFlag"))
        self.verticalLayout_3.addWidget(self.RemindMeFlag)
        self.ShowPassFlag = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.ShowPassFlag.setObjectName(_fromUtf8("ShowPassFlag"))
        self.verticalLayout_3.addWidget(self.ShowPassFlag)
        self.ForgotPassBtn = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.ForgotPassBtn.setAutoDefault(True)
        self.ForgotPassBtn.setDefault(True)
        self.ForgotPassBtn.setFlat(True)
        self.ForgotPassBtn.setObjectName(_fromUtf8("ForgotPassBtn"))
        self.verticalLayout_3.addWidget(self.ForgotPassBtn)
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 331, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.hlforbtns = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.hlforbtns.setMargin(0)
        self.hlforbtns.setObjectName(_fromUtf8("hlforbtns"))
        self.EnterBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.EnterBtn.setObjectName(_fromUtf8("EnterBtn"))
        self.hlforbtns.addWidget(self.EnterBtn)
        self.RegBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.RegBtn.setMinimumSize(QtCore.QSize(112, 36))
        self.RegBtn.setAutoRepeat(False)
        self.RegBtn.setFlat(False)
        self.RegBtn.setObjectName(_fromUtf8("RegBtn"))
        self.hlforbtns.addWidget(self.RegBtn)
        self.CanselBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.CanselBtn.setObjectName(_fromUtf8("CanselBtn"))
        self.hlforbtns.addWidget(self.CanselBtn)
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.db_bulb_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.db_bulb_label.setAlignment(QtCore.Qt.AlignCenter)
        self.db_bulb_label.setObjectName(_fromUtf8("db_bulb_label"))
        self.verticalLayout.addWidget(self.db_bulb_label)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.page_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 531, 431))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 300))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 400))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(40, 30, 225, 231))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.NewNameLine = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.NewNameLine.setObjectName(_fromUtf8("NewNameLine"))
        self.verticalLayout_7.addWidget(self.NewNameLine)
        self.NewPassLine = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.NewPassLine.setObjectName(_fromUtf8("NewPassLine"))
        self.verticalLayout_7.addWidget(self.NewPassLine)
        self.RepPassLine = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.RepPassLine.setObjectName(_fromUtf8("RepPassLine"))
        self.verticalLayout_7.addWidget(self.RepPassLine)
        self.NewDateEdit = QtGui.QDateEdit(self.verticalLayoutWidget_4)
        self.NewDateEdit.setCalendarPopup(True)
        self.NewDateEdit.setObjectName(_fromUtf8("NewDateEdit"))
        self.verticalLayout_7.addWidget(self.NewDateEdit)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.AccBtn = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.AccBtn.setObjectName(_fromUtf8("AccBtn"))
        self.horizontalLayout_5.addWidget(self.AccBtn)
        self.CancelBtn = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.CancelBtn.setObjectName(_fromUtf8("CancelBtn"))
        self.horizontalLayout_5.addWidget(self.CancelBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 3, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayoutWidget = QtGui.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 431))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 400))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.EMailLine = QtGui.QLineEdit(self.groupBox)
        self.EMailLine.setGeometry(QtCore.QRect(50, 100, 211, 36))
        self.EMailLine.setObjectName(_fromUtf8("EMailLine"))
        self.ChnPassBtn = QtGui.QPushButton(self.groupBox)
        self.ChnPassBtn.setGeometry(QtCore.QRect(30, 180, 131, 36))
        self.ChnPassBtn.setObjectName(_fromUtf8("ChnPassBtn"))
        self.CancelBtn_2 = QtGui.QPushButton(self.groupBox)
        self.CancelBtn_2.setGeometry(QtCore.QRect(170, 180, 103, 36))
        self.CancelBtn_2.setObjectName(_fromUtf8("CancelBtn_2"))
        self.gridLayout.addWidget(self.groupBox, 2, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 3, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.page_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(130, 0, 286, 38))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.graphicsView = QtGui.QGraphicsView(self.horizontalLayoutWidget_2)
        self.graphicsView.setMaximumSize(QtCore.QSize(30, 30))
        self.graphicsView.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout_6.addWidget(self.graphicsView)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.ChangeUserBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.ChangeUserBtn.setMinimumSize(QtCore.QSize(150, 36))
        self.ChangeUserBtn.setAutoDefault(False)
        self.ChangeUserBtn.setFlat(True)
        self.ChangeUserBtn.setObjectName(_fromUtf8("ChangeUserBtn"))
        self.horizontalLayout_6.addWidget(self.ChangeUserBtn)
        self.groupBox_3 = QtGui.QGroupBox(self.page_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 91, 461))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 121, 431))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.rb1 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb1.setIconSize(QtCore.QSize(10, 10))
        self.rb1.setCheckable(True)
        self.rb1.setChecked(False)
        self.rb1.setProperty("baseSizeAdj", QtCore.QSizeF(-1.0, -1.0))
        self.rb1.setObjectName(_fromUtf8("rb1"))
        self.verticalLayout_4.addWidget(self.rb1)
        self.rb2 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb2.setObjectName(_fromUtf8("rb2"))
        self.verticalLayout_4.addWidget(self.rb2)
        self.rb3 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb3.setObjectName(_fromUtf8("rb3"))
        self.verticalLayout_4.addWidget(self.rb3)
        self.rb4 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb4.setObjectName(_fromUtf8("rb4"))
        self.verticalLayout_4.addWidget(self.rb4)
        self.rb5 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb5.setObjectName(_fromUtf8("rb5"))
        self.verticalLayout_4.addWidget(self.rb5)
        self.rb6 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb6.setObjectName(_fromUtf8("rb6"))
        self.verticalLayout_4.addWidget(self.rb6)
        self.rb7 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb7.setObjectName(_fromUtf8("rb7"))
        self.verticalLayout_4.addWidget(self.rb7)
        self.rb8 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb8.setObjectName(_fromUtf8("rb8"))
        self.verticalLayout_4.addWidget(self.rb8)
        self.rb9 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb9.setObjectName(_fromUtf8("rb9"))
        self.verticalLayout_4.addWidget(self.rb9)
        self.rb10 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb10.setObjectName(_fromUtf8("rb10"))
        self.verticalLayout_4.addWidget(self.rb10)
        self.rb11 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb11.setObjectName(_fromUtf8("rb11"))
        self.verticalLayout_4.addWidget(self.rb11)
        self.rb12 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb12.setObjectName(_fromUtf8("rb12"))
        self.verticalLayout_4.addWidget(self.rb12)
        self.rb13 = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rb13.setObjectName(_fromUtf8("rb13"))
        self.verticalLayout_4.addWidget(self.rb13)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.tableView = QtGui.QTableView(self.page_2)
        self.tableView.setGeometry(QtCore.QRect(100, 50, 441, 391))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Окно авторизации", None))
        self.NameLine.setPlaceholderText(_translate("MainWindow", "Имя пользователя", None))
        self.PasswordLine.setPlaceholderText(_translate("MainWindow", "Пароль", None))
        self.RemindMeFlag.setText(_translate("MainWindow", "Запомнить меня", None))
        self.ShowPassFlag.setText(_translate("MainWindow", "Показать пароль", None))
        self.ForgotPassBtn.setText(_translate("MainWindow", "Забыли пароль ?", None))
        self.EnterBtn.setText(_translate("MainWindow", "Войти", None))
        self.RegBtn.setText(_translate("MainWindow", "Регистрация", None))
        self.CanselBtn.setText(_translate("MainWindow", "Отмена", None))
        self.db_bulb_label.setText(_translate("MainWindow", "Соединение не обнаруженно", None))
        self.NewNameLine.setPlaceholderText(_translate("MainWindow", "Имя пользователя", None))
        self.NewPassLine.setPlaceholderText(_translate("MainWindow", "Пароль", None))
        self.RepPassLine.setPlaceholderText(_translate("MainWindow", "Повтоите пароль", None))
        self.NewDateEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.AccBtn.setText(_translate("MainWindow", "Ok", None))
        self.CancelBtn.setText(_translate("MainWindow", "Отмена", None))
        self.label_4.setText(_translate("MainWindow", "Регистрация", None))
        self.label_3.setText(_translate("MainWindow", "Восстановление пароля", None))
        self.EMailLine.setPlaceholderText(_translate("MainWindow", "Адрес электронной почты", None))
        self.ChnPassBtn.setText(_translate("MainWindow", "Сменить пароль", None))
        self.CancelBtn_2.setText(_translate("MainWindow", "Отмена", None))
        self.label_5.setText(_translate("MainWindow", "Авторизован", None))
        self.ChangeUserBtn.setText(_translate("MainWindow", "ИмяПользователя", None))
        self.rb1.setText(_translate("MainWindow", "АБ", None))
        self.rb2.setText(_translate("MainWindow", "ВГ", None))
        self.rb3.setText(_translate("MainWindow", "ДЕ", None))
        self.rb4.setText(_translate("MainWindow", "ЖЗИЙ", None))
        self.rb5.setText(_translate("MainWindow", "КЛ", None))
        self.rb6.setText(_translate("MainWindow", "МН", None))
        self.rb7.setText(_translate("MainWindow", "ОП", None))
        self.rb8.setText(_translate("MainWindow", "РС", None))
        self.rb9.setText(_translate("MainWindow", "ТУ", None))
        self.rb10.setText(_translate("MainWindow", "ФХ", None))
        self.rb11.setText(_translate("MainWindow", "ЦЧШЩ", None))
        self.rb12.setText(_translate("MainWindow", "ЪЫЬЭ", None))
        self.rb13.setText(_translate("MainWindow", "ЮЯ", None))

